// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xouzwbzesnxpawvgzldw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvdXp3Ynplc254cGF3dmd6bGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyODgyOTksImV4cCI6MjA1NDg2NDI5OX0.213ekfUSv0A8n7Ps_TWSedD-gcLO8bskFd0wk1E0ZAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);